[package]
name = "operation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder_derive = {git="https://github.com/ivario123/builder_derive"}
arch = {path = "../arch"}
