imports_granularity = "crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
wrap_comments = true
error_on_line_overflow = true
max_width = 300

use_field_init_shorthand = true
format_macro_matchers = true
overflow_delimited_expr = true
